project:
  name: quickstart-databricks-unified-data-analytics-platform
  owner: sshvans@amazon.com
  package_lambda: false
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
tests:
  xacctest:
    parameters:
      ExternalID: 'databricks'
      IAMRole: databricks-cross-account-role
      BucketName: test-dbrks-bkt
      TagName: 'Name=databricks'
    regions:
    - us-west-2
    template: templates/databricks-cross-account-role.template.yaml
